language: go
go:
    - tip
before_install:
    - go get github.com/modocache/gover
    - go get github.com/mattn/goveralls
    - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
    - go test ./...
    - $HOME/gopath/bin/gover
    - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci -repotoken $COVERALLS_TOKEN

env:
    global:
        secure: sNKTvsXUw5oC9djzyxBye58yRWig/4eKkYrGA+tVPHYUCkvTzJ36+egYL4/p07SKg8sp4SkxY5U9fboLkdZ/qLtQEk8f+yWlJ+X3LPOzkQIdDPey33knGq2oxBXP5I2YBeD5G0NMIlf0gWS721GlB5lAxShVG4OyVpmWJWlbBjusojfh+XDQ6kHyuGay0GsgER4Q/mRwPgwRLwGgl4YoNbtAn5jLgQeqcBBRbbu7pbp0VChu5iwXsjaoSzSzt/qg158dcYSLLTUjXygSZYRUTp8Le4wYg9mgJM7xLvqNzbvWzirtt79F7PaUKmFuutstEL4GbWypqsLbRsa5iyoJQqQLT3WkAQkjsKfaZjQKsMg3dteq9bUwhw1BFlrHq0Q8o3B46Od8YJNbdePBDOdu6X9bjLM3WE0G/jLVn6j2xL/rf+ehuGHqe0YQPxeUqv9h2wBt7SB7h6YSXD6t+QkaIBeI73R/ZYWd/xVQ8Je8HiSmQXhSJ6gibaRcbs27X5gnhr8PKAPR8m9DLcgkeQPn36llpRlOClEUaCZnDrMYyjalxSDt0lQdf+1cXXYhaYvaEah2d0u7V3CT814zw1JAGNUzHFfl1xcla9nl3aHn8HrufJnAOhPW3I+gYV75n4NVh2wCehnqn8n3la5Ortl6IhgQfTfqr/sC4rzJMlyxxo0=
